# Generated by Django 5.2.17 on 2026-09-29 14:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(blank=True, default='', verbose_name='소개')),
                ('benefit', models.CharField(blank=True, default='', max_length=200, verbose_name='혜택')),
                ('terms', models.TextField(blank=True, default='', verbose_name='이용 조건')),
                ('image_url', models.URLField(blank=True, default='', max_length=500, verbose_name='대표 이미지 URL')),
                ('starts_at', models.DateTimeField(verbose_name='발급 시작')),
                ('ends_at', models.DateTimeField(verbose_name='발급 종료')),
                ('redeem_until', models.DateTimeField(verbose_name='사용 종료')),
                ('total_quantity', models.PositiveIntegerField(verbose_name='총 발급 수량')),
                ('is_published', models.BooleanField(default=False, verbose_name='공개 여부')),
                ('featured_rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='추천 노출 순위')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='stores.store', verbose_name='매장')),
            ],
            options={
                'verbose_name': '프로모션',
                'verbose_name_plural': '프로모션',
                'db_table': 'promotions',
            },
        ),
        migrations.CreateModel(
            name='PromotionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('VIEW', '조회'), ('CHANNEL_CLICK', '채널 클릭')], max_length=20, verbose_name='이벤트 종류')),
                ('channel', models.CharField(blank=True, choices=[('', '없음'), ('instagram', '인스타그램'), ('naver', '네이버')], default='', max_length=20, verbose_name='채널')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('promotion', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='promotions.promotion', verbose_name='프로모션')),
            ],
            options={
                'verbose_name': '프로모션 이벤트',
                'verbose_name_plural': '프로모션 이벤트',
                'db_table': 'promotion_events',
            },
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(condition=models.Q(('starts_at__lt', models.F('ends_at'))), name='promotion_starts_before_ends'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__lte', models.F('redeem_until'))), name='promotion_ends_before_redeem_until'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(condition=models.Q(('total_quantity__gt', 0)), name='promotion_total_quantity_positive'),
        ),
        migrations.AddIndex(
            model_name='promotionevent',
            index=models.Index(fields=['promotion', 'created_at'], name='promo_event_promo_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='promotionevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('channel', ''), ('event_type', 'VIEW')), models.Q(('channel__in', ['instagram', 'naver']), ('event_type', 'CHANNEL_CLICK')), _connector='OR'), name='promotion_event_type_channel_valid'),
        ),
    ]
