# Generated by Django 5.2.17 on 2026-10-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='promotion',
            name='promotion_ends_before_redeem_until',
        ),
        migrations.RemoveConstraint(
            model_name='promotion',
            name='promotion_total_quantity_positive',
        ),
        migrations.AddField(
            model_name='promotion',
            name='requires_coupon',
            field=models.BooleanField(default=True, verbose_name='쿠폰 필요 여부'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='ends_at',
            field=models.DateTimeField(verbose_name='프로모션 종료'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='redeem_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='쿠폰 사용 종료'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='starts_at',
            field=models.DateTimeField(verbose_name='프로모션 시작'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='total_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='총 쿠폰 발급 수량'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(condition=models.Q(('requires_coupon', False), ('ends_at__lte', models.F('redeem_until')), _connector='OR'), name='promotion_ends_before_redeem_until'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('redeem_until__isnull', False), ('requires_coupon', True), ('total_quantity__gt', 0), ('total_quantity__isnull', False)), models.Q(('redeem_until__isnull', True), ('requires_coupon', False), ('total_quantity__isnull', True)), _connector='OR'), name='promotion_coupon_fields_valid'),
        ),
    ]
