# Generated by Django 5.2.17 on 2026-10-10 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_remove_promotion_promotion_ends_before_redeem_until_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='저장 시각')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='promotions.promotion', verbose_name='프로모션')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_promotions', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '저장한 프로모션',
                'verbose_name_plural': '저장한 프로모션',
                'db_table': 'saved_promotions',
                'indexes': [models.Index(fields=['user', '-created_at'], name='saved_promo_user_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'promotion'), name='uniq_saved_promotion_user_promotion')],
            },
        ),
    ]
