# Generated by Django 5.2.17 on 2026-09-29 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='닉네임'),
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('kakao', '카카오')], max_length=20, verbose_name='제공자')),
                ('provider_user_id', models.CharField(max_length=64, verbose_name='제공자 사용자 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '소셜 계정',
                'verbose_name_plural': '소셜 계정',
                'db_table': 'social_accounts',
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_user_id'), name='uniq_social_account_provider_user_id'), models.UniqueConstraint(fields=('user', 'provider'), name='uniq_social_account_user_provider')],
            },
        ),
    ]
