# Generated by Django 5.2.17 on 2026-09-29 14:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promotions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='발급 시각')),
                ('expires_at', models.DateTimeField(verbose_name='사용 기한')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='사용 시각')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupons', to='promotions.promotion', verbose_name='프로모션')),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='coupons', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '쿠폰',
                'verbose_name_plural': '쿠폰',
                'db_table': 'coupons',
                'constraints': [models.UniqueConstraint(fields=('user', 'promotion'), name='uniq_coupon_user_promotion')],
            },
        ),
    ]
