# Generated by Django 5.2.17 on 2026-10-08 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PinAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_count', models.PositiveSmallIntegerField(default=0, verbose_name='연속 실패 횟수')),
                ('first_failed_at', models.DateTimeField(blank=True, null=True, verbose_name='첫 실패 시각')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='차단 해제 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pin_attempts', to='stores.store', verbose_name='매장')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pin_attempts', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': 'PIN 실패 기록',
                'verbose_name_plural': 'PIN 실패 기록',
                'db_table': 'coupon_pin_attempts',
                'constraints': [models.UniqueConstraint(fields=('user', 'store'), name='uniq_pin_attempt_user_store')],
            },
        ),
    ]
