"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

import environ


# 프로젝트 기준 경로
BASE_DIR = Path(__file__).resolve().parent.parent


# 환경변수의 자료형과 기본값
env = environ.Env(
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, ['localhost', '127.0.0.1']),
    CORS_ALLOWED_ORIGINS=(list, []),
    CSRF_TRUSTED_ORIGINS=(list, []),
    SESSION_COOKIE_SECURE=(bool, False),
    CSRF_COOKIE_SECURE=(bool, False),
    CSRF_COOKIE_DOMAIN=(str, ''),
    KAKAO_REST_API_KEY=(str, ''),
    KAKAO_CLIENT_SECRET=(str, ''),
    KAKAO_CLIENT_SECRET_ENABLED=(bool, True),
    KAKAO_REDIRECT_URI=(str, ''),
    FRONTEND_BASE_URL=(str, 'http://localhost:3000'),
    LINER_API_KEY=(str, ''),
    LINER_MODEL=(str, 'liner-mark-1.3'),
    DB_HOST=(str, 'localhost'),
    DB_PORT=(int, 5432),
)


# 로컬 .env 파일을 읽습니다.
# Railway 등에서 이미 설정한 환경변수는 덮어쓰지 않습니다.
environ.Env.read_env(BASE_DIR / '.env', overwrite=False)


# 실행 환경 구분
# Railway에는 APP_ENV=production을 설정합니다.
# 로컬에서 APP_ENV를 설정하지 않으면 development로 처리합니다.
IS_PRODUCTION = env('APP_ENV', default='development') == 'production'

if IS_PRODUCTION:
    SECURE_PROXY_SSL_HEADER = (
        "HTTP_X_FORWARDED_PROTO",
        "https",
    )

    SECURE_SSL_REDIRECT = True
    SECURE_REDIRECT_EXEMPT = [r"^health/$"]
    # 세션·CSRF 쿠키 Secure는 아래 'Session / CSRF cookies'에서 IS_PRODUCTION이면 True로 설정합니다.

# Django 기본 보안 설정
SECRET_KEY = env('SECRET_KEY')
DEBUG = env('DEBUG')
ALLOWED_HOSTS = env('ALLOWED_HOSTS')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'corsheaders',
    # Local
    'users',
    'stores',
    'promotions',
    'coupons',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
database_url = os.getenv("DATABASE_URL")

if database_url:
    DATABASES = {
        "default": dj_database_url.parse(
            database_url,
            conn_max_age=60,
            conn_health_checks=True,
        )
    }
elif IS_PRODUCTION:
    raise ImproperlyConfigured(
        "운영 환경에는 DATABASE_URL이 필요합니다."
    )
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ["DB_NAME"],
            "USER": os.environ["DB_USER"],
            "PASSWORD": os.environ["DB_PASSWORD"],
            "HOST": os.getenv("DB_HOST", "localhost"),
            "PORT": os.getenv("DB_PORT", "5432"),
            "CONN_MAX_AGE": 60,
            "CONN_HEALTH_CHECKS": True,
            # Windows에서 localhost가 IPv6(::1)부터 시도할 때 무한 대기하지 않도록 합니다.
            "OPTIONS": {
                "connect_timeout": 5,
            },
        }
    }

# Custom user model
# https://docs.djangoproject.com/en/5.2/topics/auth/customizing/#substituting-a-custom-user-model

AUTH_USER_MODEL = 'users.User'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True

# 날짜·숫자 형식은 config/formats/ko/formats.py에서 지정합니다.
FORMAT_MODULE_PATH = ['config.formats']

USE_THOUSAND_SEPARATOR = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (user uploads)

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# CORS / CSRF
# https://github.com/adamchainz/django-cors-headers

CORS_ALLOWED_ORIGINS = env('CORS_ALLOWED_ORIGINS')
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = env('CSRF_TRUSTED_ORIGINS')


# Session / CSRF cookies
# 소비자 인증은 Django 세션 쿠키를 씁니다. 프론트·백엔드가 같은 도메인 아래에 배포되는 것을 전제로 합니다.
# - 세션 쿠키: HttpOnly(기본값)라 JS에서 읽을 수 없습니다.
# - SameSite=Lax(기본값): 카카오에서 callback으로 돌아오는 최상위 GET 이동에도 세션 쿠키가 전송됩니다.
# - 운영(HTTPS)에서는 *_COOKIE_SECURE=True로 설정합니다.
# - CSRF_COOKIE_DOMAIN: 운영에서 프론트(godgoowm.com)가 API 서버(api.godgoowm.com)의 csrftoken 쿠키를
#   읽어야 하므로 '.godgoowm.com'처럼 상위 도메인을 지정합니다. 개발(localhost)에서는 비워 둡니다.

# 운영(APP_ENV=production)에서는 환경변수 값과 관계없이 항상 True입니다.
SESSION_COOKIE_SECURE = IS_PRODUCTION or env('SESSION_COOKIE_SECURE')
CSRF_COOKIE_SECURE = IS_PRODUCTION or env('CSRF_COOKIE_SECURE')
CSRF_COOKIE_DOMAIN = env('CSRF_COOKIE_DOMAIN') or None


# Cache
# https://docs.djangoproject.com/en/5.2/topics/cache/#database-caching
# API 요청 횟수 제한(throttle) 기록을 서버 프로세스 간에 공유하기 위해 DB 캐시를 씁니다.
# 테이블 생성: python manage.py createcachetable (Railway는 pre-deploy에서 실행)

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'django_cache',
    }
}


# Django REST framework
# https://www.django-rest-framework.org/api-guide/settings/

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 로그인된 사용자의 쓰기 요청(POST 등)에는 CSRF 검사가 적용됩니다.
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # 오류 응답 형식: {"error": {"code": ..., "message": ...}}
    'EXCEPTION_HANDLER': 'config.exceptions.custom_exception_handler',
    # 요청 횟수 제한은 전역으로 걸지 않고, 필요한 뷰에만 throttle 클래스를 지정합니다.
    # 초과 시 429 TOO_MANY_REQUESTS + Retry-After 헤더
    'DEFAULT_THROTTLE_RATES': {
        'coupon_issue': '10/min',  # 쿠폰 발급: 로그인 사용자별 분당 10회
    },
    'DATETIME_FORMAT': '%Y-%m-%dT%H:%M:%S%z',
    'DATE_FORMAT': '%Y-%m-%d',
    'TIME_FORMAT': '%H:%M:%S',
}


# Kakao login
# https://developers.kakao.com/docs/ko/kakaologin/rest-api
# 키가 없어도 서버는 실행되며, 카카오 로그인 요청 시에만 설정 누락 오류를 냅니다.

KAKAO_REST_API_KEY = env('KAKAO_REST_API_KEY')
# 카카오 앱의 Client Secret은 기본값이 '사용함'이며, 이 경우 토큰 요청에 반드시 포함해야 합니다.
# 콘솔에서 '사용 안 함'으로 바꾼 경우에만 KAKAO_CLIENT_SECRET_ENABLED=False로 둡니다.
KAKAO_CLIENT_SECRET = env('KAKAO_CLIENT_SECRET')
KAKAO_CLIENT_SECRET_ENABLED = env('KAKAO_CLIENT_SECRET_ENABLED')
# 카카오 콘솔에 등록한 Redirect URI와 정확히 같아야 합니다.
KAKAO_REDIRECT_URI = env('KAKAO_REDIRECT_URI')
# 로그인 후 돌아갈 프론트엔드 주소 (끝에 / 없이)
FRONTEND_BASE_URL = env('FRONTEND_BASE_URL').rstrip('/')

# Liner Model API (Django Admin 프로모션 문구 초안 생성 전용)
# 키가 없어도 서버는 실행되며, 관리자가 초안 생성을 요청할 때만 안전하게 실패합니다.
LINER_API_KEY = env('LINER_API_KEY')
LINER_MODEL = env('LINER_MODEL')
