"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Environment variables
# 프로젝트 루트의 .env 파일을 읽습니다. 이미 설정된 OS 환경변수가 우선합니다.
env = environ.Env(
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, []),
    CORS_ALLOWED_ORIGINS=(list, []),
    CSRF_TRUSTED_ORIGINS=(list, []),
    SESSION_COOKIE_SECURE=(bool, False),
    CSRF_COOKIE_SECURE=(bool, False),
    CSRF_COOKIE_DOMAIN=(str, ''),
    KAKAO_REST_API_KEY=(str, ''),
    KAKAO_CLIENT_SECRET=(str, ''),
    KAKAO_CLIENT_SECRET_ENABLED=(bool, True),
    KAKAO_REDIRECT_URI=(str, ''),
    FRONTEND_BASE_URL=(str, 'http://localhost:5173'),
    DB_HOST=(str, 'localhost'),
    DB_PORT=(int, 5432),
)
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env('ALLOWED_HOSTS')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'corsheaders',
    # Local
    'users',
    'stores',
    'promotions',
    'coupons',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
        'CONN_MAX_AGE': 60,
        'CONN_HEALTH_CHECKS': True,
        'OPTIONS': {
            'connect_timeout': 5,
        },
    }
}


# Custom user model
# https://docs.djangoproject.com/en/5.2/topics/auth/customizing/#substituting-a-custom-user-model

AUTH_USER_MODEL = 'users.User'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True

# 날짜·숫자 형식은 config/formats/ko/formats.py에서 지정합니다.
FORMAT_MODULE_PATH = ['config.formats']

USE_THOUSAND_SEPARATOR = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (user uploads)

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# CORS / CSRF
# https://github.com/adamchainz/django-cors-headers

CORS_ALLOWED_ORIGINS = env('CORS_ALLOWED_ORIGINS')
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = env('CSRF_TRUSTED_ORIGINS')


# Session / CSRF cookies
# 소비자 인증은 Django 세션 쿠키를 씁니다. 프론트·백엔드가 같은 도메인 아래에 배포되는 것을 전제로 합니다.
# - 세션 쿠키: HttpOnly(기본값)라 JS에서 읽을 수 없습니다.
# - SameSite=Lax(기본값): 카카오에서 callback으로 돌아오는 최상위 GET 이동에도 세션 쿠키가 전송됩니다.
# - 운영(HTTPS)에서는 *_COOKIE_SECURE=True로 설정합니다.
# - CSRF_COOKIE_DOMAIN: 운영에서 프론트(godgoowm.com)가 API 서버(api.godgoowm.com)의 csrftoken 쿠키를
#   읽어야 하므로 '.godgoowm.com'처럼 상위 도메인을 지정합니다. 개발(localhost)에서는 비워 둡니다.

SESSION_COOKIE_SECURE = env('SESSION_COOKIE_SECURE')
CSRF_COOKIE_SECURE = env('CSRF_COOKIE_SECURE')
CSRF_COOKIE_DOMAIN = env('CSRF_COOKIE_DOMAIN') or None


# Django REST framework
# https://www.django-rest-framework.org/api-guide/settings/

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 로그인된 사용자의 쓰기 요청(POST 등)에는 CSRF 검사가 적용됩니다.
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # 오류 응답 형식: {"error": {"code": ..., "message": ...}}
    'EXCEPTION_HANDLER': 'config.exceptions.custom_exception_handler',
    'DATETIME_FORMAT': '%Y-%m-%dT%H:%M:%S%z',
    'DATE_FORMAT': '%Y-%m-%d',
    'TIME_FORMAT': '%H:%M:%S',
}


# Kakao login
# https://developers.kakao.com/docs/ko/kakaologin/rest-api
# 키가 없어도 서버는 실행되며, 카카오 로그인 요청 시에만 설정 누락 오류를 냅니다.

KAKAO_REST_API_KEY = env('KAKAO_REST_API_KEY')
# 카카오 앱의 Client Secret은 기본값이 '사용함'이며, 이 경우 토큰 요청에 반드시 포함해야 합니다.
# 콘솔에서 '사용 안 함'으로 바꾼 경우에만 KAKAO_CLIENT_SECRET_ENABLED=False로 둡니다.
KAKAO_CLIENT_SECRET = env('KAKAO_CLIENT_SECRET')
KAKAO_CLIENT_SECRET_ENABLED = env('KAKAO_CLIENT_SECRET_ENABLED')
# 카카오 콘솔에 등록한 Redirect URI와 정확히 같아야 합니다.
KAKAO_REDIRECT_URI = env('KAKAO_REDIRECT_URI')
# 로그인 후 돌아갈 프론트엔드 주소 (끝에 / 없이)
FRONTEND_BASE_URL = env('FRONTEND_BASE_URL').rstrip('/')
