# Generated by Django 5.2.17 on 2026-09-29 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='매장명')),
                ('category', models.CharField(choices=[('BAKERY_CAFE', '베이커리·카페'), ('RESTAURANT', '음식점')], max_length=20, verbose_name='카테고리')),
                ('address', models.CharField(max_length=255, verbose_name='주소')),
                ('business_hours', models.TextField(blank=True, default='', verbose_name='영업시간·휴무 안내')),
                ('image_url', models.URLField(blank=True, default='', max_length=500, verbose_name='대표 이미지 URL')),
                ('story', models.TextField(blank=True, default='', verbose_name='매장 소개')),
                ('promotion_context', models.TextField(blank=True, default='', verbose_name='내부 운영 메모')),
                ('map_url', models.URLField(blank=True, default='', max_length=500, verbose_name='지도 링크')),
                ('instagram_url', models.URLField(blank=True, default='', max_length=500, verbose_name='인스타그램 링크')),
                ('naver_url', models.URLField(blank=True, default='', max_length=500, verbose_name='네이버 링크')),
                ('usage_pin_hash', models.CharField(blank=True, default='', max_length=128, verbose_name='사용 PIN 해시')),
                ('pin_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='PIN 변경 시각')),
                ('is_active', models.BooleanField(default=True, verbose_name='운영 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
            ],
            options={
                'verbose_name': '매장',
                'verbose_name_plural': '매장',
                'db_table': 'stores',
            },
        ),
        migrations.CreateModel(
            name='StoreAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True, verbose_name='토큰 해시')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 가능')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='만료 시각')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='최근 사용 시각')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='stores.store', verbose_name='매장')),
            ],
            options={
                'verbose_name': '매장 접근 토큰',
                'verbose_name_plural': '매장 접근 토큰',
                'db_table': 'store_access_tokens',
            },
        ),
        migrations.CreateModel(
            name='StoreMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='메뉴명')),
                ('price', models.PositiveIntegerField(verbose_name='가격(원)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='표시 순서')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='stores.store', verbose_name='매장')),
            ],
            options={
                'verbose_name': '매장 메뉴',
                'verbose_name_plural': '매장 메뉴',
                'db_table': 'store_menus',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
