# Generated by Django 5.2.17 on 2026-10-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='story_after_image',
            field=models.TextField(blank=True, default='', verbose_name='이미지 이후 이야기'),
        ),
        migrations.AddField(
            model_name='store',
            name='story_image_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='가게 이야기 이미지 URL'),
        ),
        migrations.AddField(
            model_name='store',
            name='story_title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='가게 이야기 제목'),
        ),
        migrations.AddField(
            model_name='storemenu',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='메뉴 설명'),
        ),
        migrations.AddField(
            model_name='storemenu',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='메뉴 이미지 URL'),
        ),
    ]
